config/routes.rb
Rails.application.routes.draw do

  get 'set_language/english'
  get 'set_language/czech'

  # namespace :admin do
  #   resources :users
  #   root to: "users#index"
  # end

  devise_for :users

  resources :users
  resources :venues
  resources :regions
  resources :categories
  resources :events do
    resources :images
  end
  resources :events
  resources :favorite_events, path: "/favorite"
  root to: 'events#index'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :text             default("")
#  start_time   :datetime
#  end_time     :datetime
#  venue_id     :integer
#  category_id  :integer
#  organizer_id :integer
#  slug         :string
#  position     :integer
#  accepted     :boolean
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Event < ActiveRecord::Base
  has_many :images
  belongs_to :category
  belongs_to :venue
  belongs_to :organizer, :class_name => "User"

  validates_associated :category, :organizer, :venue
  validates :title, :description, :start_time, :end_time, presence: true

  # Named scopes
  scope :after_date, lambda { |date|
    where(["start_time >= ?", date]).order(:start_time)
  }
  scope :on_or_after_date, lambda { |date|
    time = date.beginning_of_day
    where("(events.start_time >= :time) OR (events.end_time IS NOT NULL AND events.end_time > :time)",
      :time => time).order(:start_time)
  }
  scope :before_date, lambda { |date|
    time = date.beginning_of_day
    where("start_time < :time", :time => time).order(start_time: :desc)
  }
  scope :future, lambda { on_or_after_date(Time.zone.today) }
  scope :past, lambda { before_date(Time.zone.today) }
  scope :within_dates, lambda { |start_date, end_date|
    if start_date == end_date
      end_date = end_date + 1.day
    end
    on_or_after_date(start_date).before_date(end_date)
  }
  scope :in_categories, lambda { |categories|
    where(category_id: categories)
  }
  scope :in_regions, lambda { |region|
    joins(:venue).where(:venues => {region_id: region})
  }
end

app/models/event/overview.rb
class Event < ActiveRecord::Base
  class Overview
    def today
      Event.within_dates(today_date, tomorrow_date)
    end

    def tomorrow
      Event.within_dates(tomorrow_date, after_tomorrow_date)
    end

    def later
      Event.within_dates(after_tomorrow_date, future_cutoff_date)
    end

    def more
      Event.after_date(future_cutoff_date).first
    end

    def tags
      @tags ||= Event.tag_counts_on(:tags, limit: 100, conditions: "tags_count >= 10").sort_by(&:name)
    end

    private

    def today_date
      @today_date ||= Time.zone.now.beginning_of_day
    end

    def tomorrow_date
      today_date + 1.day
    end

    def after_tomorrow_date
      tomorrow_date + 1.day
    end

    def future_cutoff_date
      today_date + 2.weeks
    end
  end
end

app/controllers/events_controller.rb
# == Schema Information
#
# Table name: events
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :text             default("")
#  start_time   :datetime
#  end_time     :datetime
#  venue_id     :integer
#  category_id  :integer
#  organizer_id :integer
#  slug         :string
#  position     :integer
#  accepted     :boolean
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index

    @events = Event.all.page(params[:page])

    # TODO Refactor this mess!!!!!!! Maybe use some gem? Maybe create Search model?

    # Dates
    @events = Event.within_dates(Time.parse(params[:start_time]), Time.parse(params[:end_time]))
                   .page(params[:page]) if params[:start_time].present? && params[:end_time].present?

    # Regions
    @events = Event.in_regions(params[:region])
                   .page(params[:page]) if params[:region].present?

    # Categories
    @events = Event.in_categories(params[:category])
                   .page(params[:page]) if params[:category].present?

    # Regions && Categories
    @events = Event.in_categories(params[:category])
                   .in_regions(params[:region])
                   .page(params[:page]) if params[:category].present? && params[:region].present?

    # Dates && Regions
    @events = Event.within_dates(Time.parse(params[:start_time]), Time.parse(params[:end_time]))
                   .in_regions(params[:region])
                   .page(params[:page]) if params[:region].present? && params[:start_time].present? && params[:end_time].present?

    # Dates && Categories
    @events = Event.in_categories(params[:category])
                   .within_dates(Time.parse(params[:start_time]), Time.parse(params[:end_time]))
                   .page(params[:page]) if params[:category].present? && params[:start_time].present? && params[:end_time].present?

    # Dates && Regions && Categories
    @events = Event.within_dates(Time.parse(params[:start_time]), Time.parse(params[:end_time]))
                   .in_regions(params[:region])
                   .in_categories(params[:category])
                   .page(params[:page]) if params[:category].present? && params[:region].present? && params[:start_time].present? && params[:end_time].present?

  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    authorize @event
  end

  # POST /events
  # POST /events.json
  def create
    authorize Event
    if current_user
      @event = current_user.events.new(event_params)
    else
      @event = Event.new(event_params)
    end


    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    authorize @event

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    authorize @event

    @event.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_time, :end_time, :venue_id, :category_id, :region_id, :slug, :position, :accepted)
    end
end

app/helpers/events_helper.rb
# == Schema Information
#
# Table name: events
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :text             default("")
#  start_time   :datetime
#  end_time     :datetime
#  venue_id     :integer
#  category_id  :integer
#  organizer_id :integer
#  slug         :string
#  position     :integer
#  accepted     :boolean
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

module EventsHelper
end

app/views/events/_category_select.html.erb
<div class="select-wrapper select-wrapper-categories">
  <label class="button-categories select-button category-" for="category">Všechny kategorie</label>
  <div class="categories-backdrop window-backdrop hide"></div>


  <div class="select-categories-wrapper select-window-wrapper">
    <ul class="select-categories no-style select-window">
      <li class="confirmSelect">
        <div class="submitSelect">Potvrdit</div>
        <div class="cancelSelect">Zrušit</div>
            <div class="submitSelect f-left">
              <label for="category_nil">Všechny kategorie</label>
            </div>
        <div class="clearfix"></div>
      </li>
      <% Category.all.each do |k| %>
          <li>
            <%#= radio_button_tag "category", k.id, params[:category] ? params[:category].include?("#{k.id}") : false, id: :"category_#{k.id}" %>
            <%= check_box_tag "category[]", k.id, (params[:category] ? params[:category].include?("#{k.id}") : (params[:id] == k.slug ? true : false)), id: :"category_#{k.id}" %>
            <%= label_tag :"category_#{k.id}", k.name %>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= select("event", "category_id", Category.all.collect {|c| [ c.name, c.id ] }, {include_blank: 'None'}) %>
  </div>
  <div class="field">
    <%= f.label :venue_id %><br>
    <%= select("event", "venue_id", Venue.all.collect {|c| [ c.name, c.id ] }, {include_blank: 'None'}) %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br>
    <%= f.check_box :accepted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_select_form.html.erb
<%= form_tag events_path, method: 'get', class: "select-form", id: "main_search_form" do %>
    <%= hidden_field_tag :delete_text, nil %>
    <input type="hidden" name="delete_text" id="delete_text">

    <%= render "category_select" %>

    <div class="select-wrapper select-wrapper-regions">
      <label class="button-regions select-button" for="region">Česká republika</label>
      <div class="regions-backdrop window-backdrop hide"></div>
      <div class="select-regions-wrapper select-window-wrapper">
        <div class="select-regions select-window">
          <div class="arrow"></div>
          <div class="confirmSelect">
            <div class="cancelSelect">Zrušit</div>
            <div class="submitSelect">Potvrdit</div>
            <div class="clearfix"></div>
          </div>
          <div class="select-map">
            <div class="box-ratio-for-map">
              <div class="content-ratio">


              <%= render "czech_map" %>

              </div>
            </div>
          </div>
          <ul class="select-map-list no-style">
            <li>
              <label for="region_reset" class="region-no">Česká republika</label>
            </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_0" value="0">
                  <label for="region_0">Praha</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_10" value="10">
                  <label for="region_10">Středočeský</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_11" value="11">
                  <label for="region_11">Ústecký</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_5" value="5">
                  <label for="region_5">Liberecký</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_6" value="6">
                  <label for="region_6">Moravskoslezský</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_3" value="3">
                  <label for="region_3">Karlovarský</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_4" value="4">
                  <label for="region_4">Královéhradecký</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_7" value="7">
                  <label for="region_7">Olomoucký</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_9" value="9">
                  <label for="region_9">Plzeňský</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_8" value="8">
                  <label for="region_8">Pardubický</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_13" value="13">
                  <label for="region_13">Zlínský</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_1" value="1">
                  <label for="region_1">Jihočeský</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_12" value="12">
                  <label for="region_12">Vysočina</label>
                </li>
                <li>
                  <input type="checkbox" name="region[]" id="region_2" value="2">
                  <label for="region_2">Jihomoravský</label>
                </li>
            <div class="clearfix"></div>
          </ul>
        </div>
      </div>
    </div>

    <div class="select-wrapper select-wrapper-date">
      <%= label_tag 'date', get_date_label_value,
                    class: "button-date select-button datetimerange" %>
      <div class="date-backdrop window-backdrop hide"></div>
      <div class="sselect-date-wrapper sselect-window-wrapper">
        <div class="sselect-date sselect-window">
          <%#= label_tag 'date_from', t('search.date_from_label') %>
          <%= hidden_field_tag :start_time, nil %>
          <%#= text_field_tag :date_from, nil, class: "datepicker-1 input-group" %>
          <!-- <div class="datepicker-1"></div> -->
          <%#= datetime_field_tag :date_from %>
          <%#= label_tag 'date_to', t('search.date_to_label') %>
          <%= hidden_field_tag :end_time, nil %>
          <%#= text_field_tag :date_to, nil, class: "datepicker-2 input-group" %>
          <!-- <div class="datepicker-2"></div> -->
          <%#= datetime_field_tag :date_to %>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="select-search-wrapper">
      <div class="select-search">
        <label for="text">NAJDĚTE SI CO CHCETE DĚLAT</label>
        <input type="text" name="text" id="text" placeholder="Vyhledávejte..." data-autocompletepath="/udalosti/autocomplete" class="ui-autocomplete-input" autocomplete="off">
        <input type="submit" name="commit" value="Vyhledat" delete_text="1">
      </div>
    </div>

    <div class="banners-search">
      <%= link_to root_path, target: "_blank" do %>
        <%= image_tag("/system/images/banner_Veganske_hody_Brno_2015.gif") %>
      <% end %>
    </div>

    <div class="clearfix"></div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= render 'select_form' %>

<p id="notice"><%= notice %></p>

<div class="row categories-all">
  <% Category.all.each do |category| %>
    <div id="category_<%= category.id %>" class="category-card category-<%= category.slug %> position-<%= category.position %>">
      <div class="category-card-border"></div>
      <div class="category-card-content">
        <div class="category-card-content-inner">
          <%#= link_to refinery.categories_category_path(category), class: "card-head" do %>
            <div class="category-button"><%= category.name %></div>
          <%# end %>
          <ul class="category-card-list no-style">
            <% category.top_events.each do |event| %>
              <li><%= link_to event.title, event_path(event) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>
<br>
<br>

<div class="clearfix"></div>


<div class="row">
  
  <%= paginate @events %>

  <br>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Category</th>
        <th>Description</th>
        <th>Start Time</th>
        <th>Venue</th>
        <th>Region</th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= link_to event.title, event %></td>
          <td><%= link_to event.category.name, event.category %></td>
          <td><%= event.description %></td>
          <td><%= event.start_time %></td>
          <td><%= link_to event.venue.name, event.venue %></td>
          <td><%= link_to event.venue.region.name, event.venue.region %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<br>

<% if user_signed_in? %>
<p>
  <%= button_to "Add to Favorites", controller: "favorite_events", action: "create", favorite_event: {event_id: @event.id} %>
</p>
<% else %>
  <p>
    <strong>Sign in to add this event to your favorites</strong>
  </p>
<% end %>

<br>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Date from:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>Date to:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Organizer:</strong>
  <%= link_to @event.organizer.email, @event.organizer %>
</p>

<p>
  <strong>Venue:</strong>
  <%= link_to @event.venue.name, @event.venue %>
</p>

<p>
  <strong>Category:</strong>
  <%= link_to @event.category.name, @event.category %>
</p>

<p>
  <strong>Region:</strong>
  <%= link_to @event.venue.region.name, @event.venue.region %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @event.slug %>
</p>

<p>
  <strong>Position:</strong>
  <%= @event.position %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @event.accepted %>
</p>

<p>
  <strong>Image</strong>
  <img src="<%= @event.images.first.try(:link) %>" alt="Event image" />
</p>

<% if current_user && policy(@event).update? %>
  <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', events_path %>