config/routes.rb
Rails.application.routes.draw do

  get 'set_language/english'
  get 'set_language/czech'

  # namespace :admin do
  #   resources :users
  #   root to: "users#index"
  # end

  devise_for :users

  resources :users
  resources :venues
  resources :regions
  resources :categories
  resources :events do
    resources :images
  end
  resources :events
  resources :favorite_events, path: "/favorite"
  root to: 'events#index'

end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id         :integer          not null, primary key
#  event_id   :integer
#  link       :string           default("")
#  primary    :boolean
#  caption    :string           default("")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Image < ActiveRecord::Base
  belongs_to :event
end

app/controllers/images_controller.rb
# == Schema Information
#
# Table name: images
#
#  id         :integer          not null, primary key
#  event_id   :integer
#  link       :string           default("")
#  primary    :boolean
#  caption    :string           default("")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.where({event_id: params[:event_id]})
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully added.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    def set_event
      @image = Event.find(params[:event_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:event_id, :path, :primary, :caption)
    end
end

app/helpers/images_helper.rb
# == Schema Information
#
# Table name: images
#
#  id         :integer          not null, primary key
#  event_id   :integer
#  link       :string           default("")
#  primary    :boolean
#  caption    :string           default("")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :primary %><br>
    <%= f.check_box :primary %>
  </div>
  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Link</th>
      <th>Primary</th>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.event_id %></td>
        <td><%= image.link %></td>
        <td><%= image.primary %></td>
        <td><%= image.caption %></td>
        <td><%= link_to 'Show', event_image(image) %></td>
        <td><%= link_to 'Edit', edit_image_event_path(image) %></td>
        <td><%= link_to 'Destroy', event_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_event_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @image.event_id %>
</p>

<p>
  <strong>Path:</strong>
  <%= @image.link %>
</p>

<p>
  <strong>Primary:</strong>
  <%= @image.primary %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @image.caption %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>