config/routes.rb
Rails.application.routes.draw do

  get 'set_language/english'
  get 'set_language/czech'

  # namespace :admin do
  #   resources :users
  #   root to: "users#index"
  # end

  devise_for :users

  resources :users
  resources :venues
  resources :regions
  resources :categories
  resources :events do
    resources :images
  end
  resources :events
  resources :favorite_events, path: "/favorite"
  root to: 'events#index'

end

app/views/layouts/OLD_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" href="/">
              <img src="/assets/logo.png" alt="CoBudemeDelat?" />
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

              <ul class="nav navbar-nav navbar-right main-nav">
                  <% if user_signed_in? %>
                    <li><%= link_to "Favorites", favorite_events_path %></li>
                  <% end %>
                  <li>
                      <%= link_to "Events", events_path%>
                  </li>
                  <li>
                      <%= link_to "Categories", categories_path%>
                  </li>
                  <li>
                      <%= link_to "Venues", venues_path%>
                  </li>
                  <% if user_signed_in? %>
                    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
                    <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
                  <% else %>
                    <li><%= link_to 'Sign in', new_user_session_path %></li>
                    <li><%= link_to 'Sign up', new_user_registration_path %></li>
                  <% end %>
                  <% if user_signed_in? %>
                    <% if current_user.try(:admin?) %>
                      <li><%= link_to 'Users', users_path %></li>
                    <% end %>
                  <% end %>
              </ul>

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<h1>
  <%= link_to root_path do %><%= image_tag("logo.png", class: "logo-main") %><% end %>
</h1>

<nav id="menu" class="menu">
  <ul class="no-style">
    <li class="first"><%= link_to 'Venues', venues_path, class: "link_4" %></li>
    <li><%= link_to 'Favorites', favorite_events_path, class: "link_4" %></li>
    <li><%= link_to 'Add event', new_event_path, class: "link_7" %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'Edit account', edit_user_registration_path %></li>
      <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
    <% else %>
      <li><%= link_to 'Sign in', new_user_session_path %></li>
      <li><%= link_to t('sign_up'), new_user_registration_path %></li>
    <% end %>
  </ul>
</nav>

<div class="clearfix"></div>
<div id="flash_wrapper"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  </head>
  <body id="vitejte-page" class="fullwidth ">
    <div id="page_container" class="fullwidth">
      <header id="header">
        <%= render 'layouts/navigation' %>
      </header>
      <%= render 'layouts/messages' %>
      <section id="page">
        <%= yield %>
      </section>
      <footer>
        <p>
        <%= link_to_unless I18n.locale == :en, "English", set_language_english_path %>
        |
        <%= link_to_unless I18n.locale == :cs, "Czech", set_language_czech_path %>
        </p>
      </footer>
    </div>
  </body>
</html>